# HW 7 - Libraries + Modules
ULAB - Physics and Astronomy Division \
Due **Wednesday, November 6th, 2024 at 11:59pm** on Gradescope

--------------------------------------------------------------

## Module vs. Package vs. Library
### Module
A **module** is a single file containing Python code (typically ending in a `.py` extension) that contains functions and variables. 
- They can be imported into other Python files or notebooks
- You use modules to organize code into smaller, reuseable parts
- Ex: `even_sum.py` that we created during lecture.

*You will create your OWN module for this homework and use that we made during class.*

### Package
A **package** is a group of modules, organized like a directory. 
- A package requires a special `__init__.py` file to tell Python that the ENTIRE directory is something you would like to import.
- Packages can contain sub-pacakges
- Ex: `BAGLE_Microlensing` is an example of a package (if you are in Dex's group, this should be familar to you). Or you could think of `paarti` if you are in Brianna's group.

*You will NOT be working with a package for this homework.*

### Library
A **library** is a much broader term that also refers to a collection of modules (like a package) but a library can also contain mulitple packages. 
- Libraries serve a much wider range of functionality for
- Programmers use packages to have ready-to-go tools that can be used for data manipulation, web development, machine learning or simulations.
- Ex: `numpy` is a very common library. Later in this course we will also be working some of the following libraries `matplotlib`, `scipy`, and `astropy`, `pandas`, etc

*You WILL be working with the extensive numpy library for this homework!*

--------------------------------------------------------------

# 1 NumPy
**NumPy** (aka Numerical Python) is a library that was designed for caring out computations in Python. 

We did not have a ton of time to work through examples during class, so I will ask that you check out this website for more information: https://numpy.org/doc/ 

Before we can work through any problems, you need to call the following in your notebook:

In [1]:
import numpy as np

## 1.1 Lists vs. Arrays
*When I first started working with NumPy I didn't understand what was so special about arrays. This homework problem should help illustrate the difference. Make sure to follow each step and follow good coding practices.*

1) Make a list called `my_list` and make an array called `my_arr` with the same values. There is an example below, but don't copy mine! Ex:
```
my_list = [11, 12, 13, 14, 15]
my_arr = np.array([11, 12, 13, 14, 15])
```
*Notice that to use the `numpy` package we had to call its short cut `np` and then call upon its funciton `.array()`. This is similar to working with a built-in python function like `.append()`.*

In [2]:
# Your code here

my_list = [3, 4, 5, 6, 7]
my_arr = np.array([18, 17, 16, 15, 14])

2) Multiply `my_list` by 4 and multiply `my_arr` by 4. Print the results. Describe what happens in a comment.

In [5]:
# Your code here

print(my_list * 4) # repeats the list 4 times in a new list
print(my_arr * 4) # multiplies each element by 4

[3, 4, 5, 6, 7, 3, 4, 5, 6, 7, 3, 4, 5, 6, 7, 3, 4, 5, 6, 7]
[72 68 64 60 56]


3) Add `my_list` with `my_list`. Add `my_arr` with `my_arr`. Add `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [11]:
# Your code here

print(my_list + my_list) # prints a new list with 2 copies of my_list
print(my_arr + my_arr) # adds arrays element-wise
print(my_list + my_arr) # because both the list and the array have the same number of elements they can be added and result in element-wise addition

[3, 4, 5, 6, 7, 3, 4, 5, 6, 7]
[36 34 32 30 28]
[21 21 21 21 21]


4) Subtract `my_list` with `my_list`. Subtract `my_arr` with `my_arr`. Subtract `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [14]:
# Your code here

print(my_arr - my_arr) # subtracts arrays element-wise
print(my_list - my_arr) # subtracts the list and array element-wise
print(my_list - my_list) # presents a type error because - is not defined for lists

[0 0 0 0 0]
[-15 -13 -11  -9  -7]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

5) Multiply `my_list` with `my_list`. Multply `my_arr` with `my_arr`. Multiply `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [15]:
# Your code here
print(my_arr * my_arr) # multiplies arrays element-wise
print(my_list * my_arr) # multiplies the list and array element-wise
print(my_list * my_list) # presents a type error because multiplication is not defined for lists

[324 289 256 225 196]
[54 68 80 90 98]


TypeError: can't multiply sequence by non-int of type 'list'

7) Divide `my_list` with `my_list`. Divide `my_arr` with `my_arr`. Divide `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [17]:
# Your code here
print(my_arr / my_arr) # divides arrays element-wise
print(my_list / my_arr) # divides the list and array element-wise
print(my_list / my_list) # presents a type error because division is not defined for lists

[1. 1. 1. 1. 1.]
[0.16666667 0.23529412 0.3125     0.4        0.5       ]


TypeError: unsupported operand type(s) for /: 'list' and 'list'

8) After working through this problem, in at least two sentences, describe the difference between a list and an array.

In [33]:
# Your code here

# A list can take multiple types of entries (strings, integers, other lists, etc.) while an array only takes in numerical data. This means an array is better to work with for mathematical computations.


## 1.2 Nested List and Multi-Dimensional Arrays
A **nested list** is when you have a list as an element for a list. Example:
```
nested_list = [[1, 2, 3], [4, 5, 6]]
```

A **multi-dimensional array** is essentially a nested list, but it contains the properties of a matrix. Example:
```
multi_d_array = np.array([[1, 2, 3], [4, 5, 6]])
```

Go to this website for more information on NumPy: https://www.w3schools.com/python/numpy/default.asp

Write a **function** that takes in a two-dimensional array. Example:

```
arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
```

and then returns the second value in each row. Example:

```
[4, 10, 16]
```

In [24]:
# Your code here

def second_values(array):
    # return the second value from each row
    return [row[1] for row in array]

arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
second_values(arr3)

[4, 10, 16]

In 2-3 sentences, describe what section of the website helped you write your function. 

In [ ]:
# Your comment here
# The section of the website on array indexing was what I used to write my function. I combined the idea of array indexing with a for look to loop through thr rows.

How would you take a nested list and return the second value in each row? Explain in 2-3 sentences and show an example.

In [26]:
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
second_values = [row[1] for row in nested_list]
print(second_values)

[2, 5, 8]


## 1.3 Up to You!
With the website I just gave you: https://www.w3schools.com/python/numpy/default.asp

I recommend working through the examples they provide (you don't have to do all of them, but a few would be good). It will help you build an intuition for numpy. It won't take very long, there are only a couple of examples per section.

Write you own **function** that follows the theme of one of the sections (i.e. array reshaping, array filter, random intro, etc). For example, if you are curious about the section "**NumPy Creating Arrays**" you could write a function that creates a multi-dimensional array.

```

>>> def make_multi_dimensional_array(one_d_array, dimensions):
...     # Creates a multi-dimensional array
...     # Your code here
...     return # Your code here

>>> my_one_d_array = [2, 4, 6, 8]
>>> my_dimension = 10
>>> ten_d_array = make_multi_dimensional_array(my_one_d_array, my_dimension)
>>> print(ten_d_array)
[[[[[[[[[[2 4 6 8]]]]]]]]]]

```

Your function should be more detailed than the example I gave you. Include at least one of the following: 
- a conditional statement
- an assignment operator
- a loop (`for` or `while`)
- `if`, `elif`, `else`, statement

In [33]:
# Your code here
def iterate_and_multiply_2d_array(arr, multiplier):
    # iterates over each scalar of the array and multiplies it by a multiplier you input
    multiplied_array = [] # place to store rows once they are multiplied
    for row in arr:
        multiplied_row = []  # place to store scalar elements after they are multiplied
        for scalar in row:
            multiplied_scalar = scalar * multiplier # multiply by given multiplier
            multiplied_row.append(multiplied_scalar) # add element to row
        
        multiplied_array.append(multiplied_row) # add row to array
    
    return np.array(multiplied_array)


arr = np.array([[1, 2, 3], [4, 5, 6]])
new_array = iterate_and_multiply_2d_array(arr, 3)
new_array

array([[ 3,  6,  9],
       [12, 15, 18]])

In the section you took inspiration from, show all of the examples below. Follow good coding practices and give at least two test cases for each example. Don't forget comments! \
\
*For my example, I took inspiration from **NumPy Creating Arrays** so I would show following examples with DIFFERENT test cases: Create a NumPy ndarray Object, Dimensions in Arrays ,0-D Arrays, 1-D Arrays, 2-D Arrays, 3-D Arrays, Check Number of Dimensions, Higher Dimensional Arrays.*

In [52]:
# Your code here

# access array elements
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([101, 321, 234, 985])
print(f"First element of array 1: {arr1[0]}") 
print(f"Second element of array 1: {arr1[1]}") 
print(f"First element of array 2: {arr2[0]}") 
print(f"Second element + third element of array 2: {arr2[1] + arr2[2]}")

# access 2d arrays
arr3 = np.array([[1, 2, 3, 4, 5], 
                 [6, 7, 8, 9, 10]])
arr4 = np.array([[3, 6, 9, 12, 15], 
                 [16, 17, 18, 19, 20]])
print('Second element on first row of array 3: ', arr3[0, 1]) 
print('third element on second row of array 3: ', arr3[1, 2]) 
print('fourth element on second row of array 4: ', arr4[1, 3])
print('fourth element on first row of array 4: ', arr4[0, 3]) 

#access 3d arrays
arr5 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr6 = np.array([[[15, 16, 17], [2, 1, 5]], [[1, 2, 5], [3, 1, 4]]])
print('third element of the second array of the first array in array 5:', arr5[0, 1, 2])
print('second element of the first array of the second array in array 6:', arr6[1, 0, 1]) 

#negative indexing
print('Last element from second dimension of array 3: ', arr3[1, -1]) 
print('Second to last element from first dimension of array 3: ', arr3[0, -2]) 

First element of array 1: 1
Second element of array 1: 2
First element of array 2: 101
Second element + third element of array 2: 555
Second element on first row of array 3:  2
third element on second row of array 3:  8
fourth element on second row of array 4:  19
fourth element on first row of array 4:  12
third element of the second array of the first array in array 5: 6
second element of the first array of the second array in array 6: 2
Last element from second dimension of array 3:  10
Second to last element from first dimension of array 3:  4


In 2-3 sentences, describe how your function took inspiration from a section.\
\
*For my example, `make_multi_dimensional_array`, I would talk about the **NumPy Creating Arrays** section and how I took inspiration from the example **Higher Dimensional Arrays**.*

In [53]:
# Your comment here

# My function took inspiration on this second because I was able to interate down to the scalar in my 2d array much like their example. This way, I was able to perform an operation of each scalar value in the matrix.

# 2 Brianna's Module
During lecture we created and worked with a module called `even_sum.py`. Import that module here. 

In [55]:
# Your code here
import even_sum

Now that you have imported the module. Call the module and the first function with your own list of numbers. 

In [57]:
# Your code here
numbers = [3, 6, 9, 12, 15, 18, 21, 24]
even_sum_result = even_sum.sum_even_numbers(numbers)

print("The sum of even numbers is:", even_sum_result)

The sum of even numbers is: 60


I have provided you a separate module called `example.py`. Import that module here.

In [60]:
# Your code here
import example

With the following variables, use my module to show which of the rocket's escape!

In [58]:
rocket_velocities = np.array([
    [1000, 5000, 8000, 12000],  # Rocket 1's velocity at different times
    [2000, 6000, 9000, 10000],  # Rocket 2
    [3000, 3100, 3200, 3300]    # Rocket 3
])

mass_of_planet = 5.972e24 # kilograms
radius_of_planet = 6.371e6 # meters

In [62]:
# Your code here
status = example.rocket_launch(rocket_velocities, mass_of_planet, radius_of_planet)

#print status
for i, status in enumerate(status):
    print(f"Rocket {i+1}: {status}")

Rocket 1: Rocket left the planet!
Rocket 2: Rocket is orbiting around the planet.
Rocket 3: Rocket crashes back into the planet!


In 2-3 sentences describe how this code follows "good coding practices" and where there is room for improvement.

In [ ]:
# Your comments here

# This code follows good coding practices as the function names are descriptive to what the function is doing, each function is throughly described in a comment, and the rest of the function is clean and organized. It could improve by considering restrictions such as limiting masses so that they cannot be negative. 

# 3 Your Turn!
Now its your turn to make a module! Choose a topic from a class (could be physics, computer science, nuclear engineering, biology, astronomy, math, or an topic that interests you!) and build a module around it! Look at my module called `example.py` and base your structure around it. Your module NEEDS to include the following.

Overall:
1) Your module needs to use at least one NumPy function: https://numpy.org/devdocs/reference/routines.math.html
2) Your module needs to contain a multi-dimensional array: https://numpy.org/devdocs/reference/arrays.ndarray.html 
3) Your module needs **at least** three functions that follow good coding practices.
4) Inside your function, include comments. Don't forget to describe what the function is doing and what the inputs and outputs are.
5) Your module needs either a `for` loop or `while` loop.
6) Your module needs an `if`, `elif`, and `else` statement.
7) Your module needs at least two assignment variables (`+=`, `*=`, etc).
8) Creativity. *If it looks like you plugged this whole thing into ChatGPT, I will take off points. You can use ChatGPT to help you code, but you can't use it to just do your homework for you. That's no fun :(*

In 2-3 sentences, describe the topic of your module and its capabilities. 

In [ ]:
# Your comment here

# I created a module that will calculate simple special relativity calculations. This includes the lorentz factor, time dilation, and length contraction for a given velocity along with lorentz transformations for position, time events between inertial reference frames.

In 2-3 sentences, answer the following. What was the most challenging part of building this module? What did you learn in the process that you can apply to future coding assignments?

In [30]:
# Your comment here

# Honestly, the most challenging part was coming up with an idea. I settled on this one after looking through my physics 5A notes and figuring I would have found something like this useful. As for the coding itself I found it the most difficult to make a function for the lorentz_transformation but I learned that looking through documentaion for numpy helped which I will use in future coding assignments. 

Once your module is complete, import it here.

In [69]:
# Your code here

import relativity

Call each of your functions in the cell below. Make sure to show the outputs! 

In [81]:
# Your code here
velocity_1 = 6e7 #not super close to speed of light
velocity_2 = .99 * relativity.SPEED_OF_LIGHT #very close to speed of light (more relativistic contribution)
proper_time = 10 #seconds
proper_length = 100 #meters
events = np.array([[100, 20], [200, 40], [300, 60]])  # Multiple events with (x, t) pairs stored in 2d array

lorentz_factor_1 = relativity.lorentz_factor(velocity_1)
lorentz_factor_2 = relativity.lorentz_factor(velocity_2)
print('lorentz factor 1:', lorentz_factor_1)
print('lorentz factor 2:', lorentz_factor_2)

time_dilation_1 = relativity.time_dilation(proper_time, velocity_1)
time_dilation_2 = relativity.time_dilation(proper_time, velocity_2)
print('time dilation 1:', time_dilation_1)
print('time dilation 2:', time_dilation_2)

length_contraction_1 = relativity.length_contraction(proper_length, velocity_1)
length_contraction_2 = relativity.length_contraction(proper_length, velocity_2)
print('length contraction 1:', length_contraction_1)
print('length contraction 2:', length_contraction_2)

lorentz_transformations_1 = relativity.lorentz_transformation(events, velocity_1)
lorentz_transformations_2 = relativity.lorentz_transformation(events, velocity_2)
print('lorentz transformations 1:', lorentz_transformations_1)
print('lorentz transformations 2:', lorentz_transformations_2)

lorentz factor 1: 1.020650177667622
lorentz factor 2: 7.088812050083374
time dilation 1: 10.20650177667622
time dilation 2: 70.88812050083374
length contraction 1: 97.97676244814735
length contraction 2: 14.106735979665855
lorentz transformations 1: [[-1.22478011e+09  2.04130035e+01]
 [-2.44956022e+09  4.08260070e+01]
 [-3.67434033e+09  6.12390105e+01]]
lorentz transformations 2: [[-4.20784126e+10  1.41776239e+02]
 [-8.41568252e+10  2.83552477e+02]
 [-1.26235238e+11  4.25328716e+02]]


# 4 Proper Submission
To recieve full credit for this assignment make sure you do the following:

1) Copy this homework assignment from the `ulab_2024` repository into **YOUR** local `homework7` branch. It will contain this notebook and an additional file called `example.py`. 
   
2) Follow the tasks. Make sure to run all the cells so that **all** output is visible. You will get points taken off if your ouputs are not shown!

3) Add/commit/push this notebook and **ANY** modules (so you should have `example.py` and your module) used in this homework assignment to your remote `homework7` branch. Make sure to have NOTHING else in your branch (i.e. no previous homeworks or lecture notes).

4) Do the following:
- Take a screenshot of moving **into or out** of your `homework7` brach, call it `hw7_branch`.
- Take a screenshot of calling `ls` in your `homework7` branch, it should only contain items relevent to homework 7, call it `hw7_ls`.
- Take a screenshot of adding this assignment to your local `homework7` branch, call it `hw7_add`.
- Take a screenshot of committing this assignment to your local `homework7` branch, call it `hw7_commit`.
- Take a screenshot of pushing this assignment to your remote `homework7` branch, call it `hw7_push`. 

6) Include these screenshots in your `homework7` branch. Upload your `homework7` branch to Gradescope!